@hostname = http://localhost:8091

### Create a user
POST {{hostname}}/api/users
Content-Type: application/json

{
  "email": "admin@tubely.com",
  "password": "password"
}


### Login
# @name login
POST {{hostname}}/api/login
Content-Type: application/json

{
  "email": "admin@tubely.com",
  "password": "password"
}

### Create a video
POST {{hostname}}/api/videos
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "title": "My first video",
  "description": "Test video"
}

### List videos for the logged-in user
GET {{hostname}}/api/videos
Authorization: Bearer {{login.response.body.token}}


### Reset the server (deletes all videos and thumbnails)
POST {{hostname}}/admin/reset